# Generated by Django 4.2.4 on 2023-09-02 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(14, 44, 44, 440332), verbose_name='habit starts'),
        ),
    ]
