# Generated by Django 4.2.4 on 2023-09-02 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0003_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(14, 45, 2, 264562), verbose_name='habit starts'),
        ),
    ]
